version: '3.8'

services:
  my-spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kgeet
    ports:
      - "8083:8083"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
#    depends_on:
#      - yt-dlp-server
    restart: unless-stopped

#  yt-dlp-server:
#    build:
#      context: ./yt-dlp-server  # Path to the directory with the yt-dlp Dockerfile
#      dockerfile: Dockerfile
#    container_name: yt-dlp-server
#    volumes:
#      - ./uploads:/downloads
#    ports:
#      - "5000:5000"
#    restart: unless-stopped
